### execute the following line to import numpy and rename it 

In [1]:
import numpy as np

### Create a numpy array containing the numbers from 0 to 20
1. print the last value
2. print the last 4 values
3. print every second value

In [3]:
a = np.arange(21)
print( a[-1] )
print( a[-4:] )
print( a[0::2] )

20
[17 18 19 20]
[ 0  2  4  6  8 10 12 14 16 18 20]


### Find indices of non-zero elements from [1,2,0,0,4,0]

In [20]:
a = np.array([1,2,0,0,4,0])
a.nonzero()

(array([0, 1, 4]),)

### return all values greather or equal to 2 from [1,2,0,0,4,0]

In [22]:
a[a>=2]

array([2, 4])

### Create a null vector of size 10

In [18]:
nv = np.zeros(10)
nv

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

### Create a vector containing 50 evenly spaced values between 0 and 2

In [38]:
np.arange(0,2,2./49)

array([ 0.        ,  0.04081633,  0.08163265,  0.12244898,  0.16326531,
        0.20408163,  0.24489796,  0.28571429,  0.32653061,  0.36734694,
        0.40816327,  0.44897959,  0.48979592,  0.53061224,  0.57142857,
        0.6122449 ,  0.65306122,  0.69387755,  0.73469388,  0.7755102 ,
        0.81632653,  0.85714286,  0.89795918,  0.93877551,  0.97959184,
        1.02040816,  1.06122449,  1.10204082,  1.14285714,  1.18367347,
        1.2244898 ,  1.26530612,  1.30612245,  1.34693878,  1.3877551 ,
        1.42857143,  1.46938776,  1.51020408,  1.55102041,  1.59183673,
        1.63265306,  1.67346939,  1.71428571,  1.75510204,  1.79591837,
        1.83673469,  1.87755102,  1.91836735,  1.95918367,  2.        ])

### Create a 4x4 identity matrix

In [17]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### Create a 8x8 ceckboard matrix (values 0 and 1)

In [16]:
a = np.zeros((8,8))
a[::2, ::2] = 1
a

array([[ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

### create a copy of the following matrix and set the first column to zeros.  Check that the original matrix is ualtered

In [32]:
A = np.arange(16).reshape((4,4))
B = A.copy()
B[:,0] = 0
print A
print B

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 0  5  6  7]
 [ 0  9 10 11]
 [ 0 13 14 15]]


### Create a random vector of size 10 and sort it 

In [42]:
a = np.random.rand(10)
a.sort()
a

array([ 0.08447395,  0.13274391,  0.22543458,  0.31213943,  0.47095565,
        0.68858524,  0.73299961,  0.73654291,  0.76203036,  0.87800717])

### compute the matrix product of two matrices of your choice

In [49]:
A = np.array( [[1,2,3],[4,5,6],[7,8,9]] )
B = np.array([[0,0,1],[0,1,0],[1,0,0]])
np.dot(A,B)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

### use the matrix inverse function (np.linalg.inv) to solve the following linear equation system:
* 8 x + 2 y = 24
* -4 x + y = -8

In [60]:
A = np.array([[8,2], [-4, 1]])
b = np.array( [24,-8] )

np.dot( np.linalg.inv(A), b )

array([ 2.5,  2. ])