### execute the following line to import numpy and rename it 

In [12]:
import numpy as np

### Create a numpy array containing the numbers from 0 to 20
1. print the last value
2. print the last 4 values
3. print every second value

In [20]:
a = np.arange(21)
print( a[-1] )
print( a[-4:] )
print( a[0::2] )

20
[17 18 19 20]
[ 0  2  4  6  8 10 12 14 16 18 20]


### Find indices of non-zero elements from [1,2,0,0,4,0]

In [3]:
a = np.array([1,2,0,0,4,0])

In [5]:
a.nonzero()

(array([0, 1, 4]),)

### Create a null vector of size 10

In [8]:
nv = np.zeros(10)
nv

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])